# Generated by Django 2.0.2 on 2023-07-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgpt_answer_log',
            name='create_date',
            field=models.DateTimeField(),
        ),
    ]
